name: lorawan_antares
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.6
  firebase_core: ^2.24.2
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: lib/assets/fonts/satoshi/Satoshi-Bold.otf
        - asset: lib/assets/fonts/satoshi/Satoshi-Italic.otf
        - asset: lib/assets/fonts/satoshi/Satoshi-BoldItalic.otf
        - asset: lib/assets/fonts/satoshi/Satoshi-Light.otf
        - asset: lib/assets/fonts/satoshi/Satoshi-LightItalic.otf
        - asset: lib/assets/fonts/satoshi/Satoshi-Medium.otf
        - asset: lib/assets/fonts/satoshi/Satoshi-MediumItalic.otf
